export const studentConstants = {
  // student get
  STUDENT_GET_REQUEST: "STUDENT_GET_REQUEST",
  STUDENT_GET_SUCCESS: "STUDENT_GET_SUCCESS",
  STUDENT_GET_FAILED: "STUDENT_GET_FAILED",
  
  // student add
  STUDENT_ADD_REQUEST: "STUDENT_ADD_REQUEST",
  STUDENT_ADD_SUCCESS: "STUDENT_ADD_SUCCESS",
  STUDENT_ADD_FAILED: "STUDENT_ADD_FAILED",

  // student update
  STUDENT_UPDATE_REQUEST: "STUDENT_UPDATE_REQUEST",
  STUDENT_UPDATE_SUCCESS: "STUDENT_UPDATE_SUCCESS",
  STUDENT_UPDATE_FAILED: "STUDENT_UPDATE_FAILED",

  // student delete
  STUDENT_DELETE_REQUEST: "STUDENT_DELETE_REQUEST",
  STUDENT_DELETE_SUCCESS: "STUDENT_DELETE_SUCCESS",
  STUDENT_DELETE_FAILED: "STUDENT_DELETE_FAILED",
};

export const languageConstants = {
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
}